### ISSUE TITLE
Index passed to state can sometimes be incorrect

### ISSUE THREAD

**Issue by derek-miller** [jonschlinkert/split-string#16]
Using the `state` param within the `keep()` function has the incorrect `index` when encountering a quote. Looking at the code, `state.index = i`, but then later `i` is changed without updating `state`
```
 $ node 
Welcome to Node.js v12.3.1.
Type ".help" for more information.
> const split = require('split-string');
undefined
> split('a\\"', {
...   separator: ' ',
...   quotes: ['"'],
...   keep: (value, state) => {
.....     console.log({
.......       value,
.......       prev: state.prev(),
.......       index: state.index,
.......       charAtIndex: state.input[state.index],
.......       input: state.input
.......     });
.....     if (state.input[state.index] !== value) {
.......       throw new Error()
.......     }
.....     return true;
.....   }
... });
{
  value: 'a',
  prev: undefined,
  index: 0,
  charAtIndex: 'a',
  input: 'a\\"'
}
{ value: '\\', prev: 'a', index: 1, charAtIndex: '\\', input: 'a\\"' }
{ value: '"', prev: '\\', index: 1, charAtIndex: '\\', input: 'a\\"' }
Thrown:
Error
    at keep (repl:13:13)
    at append (./node_modules/split-string/index.js:42:18)
    at module.exports (./node_modules/split-string/index.js:68:9)

```

**Comment by derek-miller** [comment]
Wait, I posted the wrong example, fixing!
